### ISSUE TITLE
Enable JSONP in WCF (feature request)

### ISSUE THREAD

**Issue by augustinmarx** [MPExtended/MPExtended#154]
To enable access to the services via JSONP (eg. to use it via jQuery getJSON) it would useful to enable JSONP. Which can be done by adding the crossDomainScriptAccessEnabled="true" attribute to the webHttpBinding.

In file MPExtended / Libraries / MPExtended.Libraries.Service / Hosting / App.config change

<pre>
&lt;webHttpBinding&gt;
&lt;binding name="general" sendTimeout="00:15:00" transferMode="Buffered"&gt;
</pre>

to

<pre>
&lt;webHttpBinding&gt;
&lt;binding name="general" sendTimeout="00:15:00" transferMode="Buffered"  crossDomainScriptAccessEnabled="true"&gt;
</pre>

Then the services can be accessed like this

<pre>
http://localhost:4322/MPExtended/TVAccessService/json/GetServiceDescription?callback=callbackfunc
</pre>

which causes the JSON data to be encapsulated in a function call to callbackfunc. This javascript function can than process the returned data.
The response to the http request would then look like this:

<pre>callbackfunc({"ApiVersion":2,"HasConnectionToTVServer":true,"ServiceVersion":"0.4.1"});</pre>

For info on JSONP: http://en.wikipedia.org/wiki/JSONP
For info on JSONP and WCF: http://msdn.microsoft.com/en-us/library/ee834511.aspx
For info on jQuery and JSON: http://api.jquery.com/jQuery.getJSON/

**Comment by oxan** [comment]
Well, I'm afraid this isn't going to work. When I add the attribute to the <webHttpBinding> tag I get the following exception on service startup:

```
2012-01-24 16:23:53.3660 [HostThread(11)] ERROR: Failed to open host MediaAccessService
(MPExtendedHost.Open => WCFHost.Start => Log.Error)
System.NotSupportedException: Cross domain javascript callback is not supported in authenticated services.
   at System.ServiceModel.Description.WebHttpBehavior.ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher)
   at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
   at System.ServiceModel.ServiceHostBase.InitializeRuntime()
   at System.ServiceModel.ServiceHostBase.OnBeginOpen()
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at MPExtended.Libraries.Service.Hosting.WCFHost.Start(IEnumerable`1 availableServices) in C:\Users\Oxan\Documents\MPExtended\Libraries\MPExtended.Libraries.Service\Hosting\WCFHost.cs:line 78
```

I can make it conditional based upon whether authentication is enabled, but not much people will want to disable authentication, and we also don't offer any option to disable it (and I don't really want to offer such a possibility either).

**Comment by augustinmarx** [comment]
Ok, sorry, I missed the authentication stuff (I'm new to MPExtend and even newer to WCF, just fiddling around and did not turn on authentication (on my local LAN I do not need it).

Sorry for that. Keep it as it is.

**Comment by augustinmarx** [comment]
Closed because of security issues.
