### ISSUE TITLE
GetAlbumBasicById() can't find album

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#166]
```
2012-01-26 16:58:00.2187 [(13)] INFO: Failed to load fileinfo for mediatype=MusicAlbum, filetype=Cover, provider=4, id=, offset=0 (resulting in path=) 
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at MPExtended.PlugIns.MAS.MPMusic.MPMusic.GetAlbumBasicById(String albumId)
   at MPExtended.Services.MediaAccessService.MediaAccessService.GetPathList(Nullable`1 provider, WebMediaType mediatype, WebFileType filetype, String id)
   at MPExtended.Services.MediaAccessService.MediaAccessService.GetFileInfo(Nullable`1 provider, WebMediaType mediatype, WebFileType filetype, String id, Int32 offset)
2012-01-26 16:58:00.2187 [(3)] INFO: Tried to stream image from non-existing source mediatype=MusicAlbum provider=4 id= filetype=Cover offset=0 
```

(MpExtended.zip, don't remember the origin of the log collection unfortunately). 

Seems to happen while loading album image, might've something to do with the space on the end.

**Comment by oxan** [comment]
Log files came from this thread: http://forum.team-mediaportal.com/mpextended-555/tv-ok-but-no-music-movies-105181/
