### ISSUE TITLE
Start/stop service doesn't work

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#80]
http://forum.team-mediaportal.com/webservice-mobile-access-537/mpextended-service-0-4-a-103873/#post824618

I experienced this too once, maybe a permission problem?

**Comment by oxan** [comment]
Seems to happen only when configurator is launched from installer.

**Comment by oxan** [comment]
```
2011-12-27 12:40:07.6462 [(1)] ERROR: Error starting uac service handler
(ServiceConfiguration.btnStartStopService_Click => UacServiceHelper.RunUacServiceHandler => Log.Error)
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MPExtended.Applications.ServiceConfigurator.Code.UacServiceHelper.RunUacServiceHandler(String _parameters)
```

Working directory seems to be wrong when started from setup. We shouldn't depend on that at all, or change it when we start.
